name: huawei_hmsavailability_example
description: Demonstrates how to use the Huawei Hmsavailability Plugin.
version: 5.2.0+301

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  huawei_hmsavailability:
    path: ../

flutter:
  uses-material-design: true
