name: huawei_ml_text
description: Huawei ML Kit Text Plugin for Flutter. Provides capabilities like Text, document, id, bank card, general card & form recognition.
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-mltext

version: 3.12.0+301

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.mltext
        pluginClass: HuaweiMlTextPlugin
