name: huawei_ml_image_example
description: Demonstrates how to use the huawei_ml_image plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_ml_image:
    path: ../
  image_picker: 0.8.4  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/user.png
    - assets/classification.png
    - assets/object.png
    - assets/landmark.png
    - assets/segmentation.png
    - assets/productsegment.png
    - assets/product.png
    - assets/imageresolution.png
    - assets/tisr.png
    - assets/scene.png
    - assets/scenedt.png
    - assets/document.png 
    - assets/addimage.png
    - assets/selectimg.png 
    - assets/textimg.png
    - assets/imgsuper.png
    - assets/banner.jpg
    