name: huawei_modeling3d_example
description: Demonstrates how to use the Huawei 3D Modeling Kit Plugin.
version: 1.1.0+300

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.3
  huawei_modeling3d:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/material_generation_images/
    - assets/3D_reconstruction_images/
