name: huawei_ml_language_example
description: Demonstrates how to use the Huawei ML Language Plugin.
version: 3.2.0+300

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  huawei_ml_language:
    path: ../
  flutter_audio_recorder2: 0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/asr.png
    - assets/langdetect.png
    - assets/rtt.png
    - assets/sounddetect.png
    - assets/trans.png
    - assets/tts.png
