name: huawei_ml_language_example
description: Demonstrates how to use the Huawei ML Language Plugin.

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_ml_language:
    path: ../
  file_picker: 4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/asr.png
    - assets/langdetect.png
    - assets/rtt.png
    - assets/sounddetect.png
    - assets/trans.png
    - assets/tts.png
