name: huawei_ml_body_example
description: Demonstrates how to use the Huawei ML Body Plugin.

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_ml_body:
    path: ../
  image_picker: 0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/face.png
    - assets/handkey.png
    - assets/liveness.png
    - assets/skeleton.png
    - assets/user.png
