name: huawei_site
description: HUAWEI Site Kit plugin for Flutter. With Huawei Site Kit, your app can provide users with convenient and secure access to diverse, place-related services.
version: 6.0.1+303
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-site

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.site
        pluginClass: SitePlugin
