name: huawei_dtm
description: Huawei DTM plugin for Flutter. With Huawei DTM, you can dynamically update tracking tags to track specific events and report data to third-party analytics platforms.
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-dtm

version: 6.6.0+303

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.dtm
        pluginClass: DTMPlugin
      ios:
        pluginClass: DTMPlugin
