name: huawei_wallet
description: Huawei Wallet Kit provides easy-to-access digital passes such as cards, coupons etc. on an integrated platform.
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-wallet

version: 4.0.5+300

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.wallet
        pluginClass: HuaweiWalletPlugin
