name: huawei_ml_image
description: HUAWEI ML Kit Image Plugin for Flutter. Provides capabilities like image classification, object detection and image super resolution.
version: 3.2.0+300
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-mlimage

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.mlimage
        pluginClass: HuaweiMlImagePlugin
