/*
 * Copyright 2020-2024. Huawei Technologies Co., Ltd. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

part of '../../huawei_iap.dart';

/// Request information of the consumeOwnedPurchase API.
class ConsumeOwnedPurchaseReq extends BaseReq {
  /// Purchase token, which is generated by the Huawei IAP server during payment and returned to the app through InAppPurchaseData.
  ///
  /// The app passes this parameter for the Huawei IAP server to update the order status and then deliver the product.
  String purchaseToken;

  /// Custom challenge, which uniquely identifies a consumption request.
  ///
  /// After the consumption is successful, the challenge is recorded in the purchase information and returned.
  ///
  /// The value length of this parameter ranges from 0 to 64.
  String? developerChallenge;

  /// Signature algorithm, which is optional.
  ///
  /// If a signature algorithm is passed, IAP will use it to sign consumption result data.
  ///
  /// Currently, the value can only be `SIGNATURE_ALGORITHM_SHA256WITHRSA_PSS`, which indicates the SHA256WithRSA/PSS algorithm.
  String? signatureAlgorithm;

  /// Creates a [ConsumeOwnedPurchaseReq] object.
  ConsumeOwnedPurchaseReq({
    required this.purchaseToken,
    this.developerChallenge,
    this.signatureAlgorithm,
    String? reservedInfor,
  }) : super(reservedInfor: reservedInfor);

  /// Creates a [ConsumeOwnedPurchaseReq] object from a JSON string.
  factory ConsumeOwnedPurchaseReq.fromJson(String str) =>
      ConsumeOwnedPurchaseReq.fromMap(json.decode(str));

  String toJson() => json.encode(toMap());

  factory ConsumeOwnedPurchaseReq.fromMap(Map<String, dynamic> json) =>
      ConsumeOwnedPurchaseReq(
        purchaseToken: json['purchaseToken'],
        developerChallenge: json['developerChallange'] == null
            ? null
            : json['developerChallange'],
        signatureAlgorithm: json['signatureAlgorithm'] == null
            ? null
            : json['signatureAlgorithm'],
        reservedInfor:
            json['reservedInfor'] == null ? null : json['reservedInfor'],
      );

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'purchaseToken': purchaseToken,
      'developerChallenge': developerChallenge,
      'signatureAlgorithm': signatureAlgorithm,
      'reservedInfor': reservedInfor,
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (this.runtimeType != other.runtimeType) return false;

    return other is ConsumeOwnedPurchaseReq &&
        this.purchaseToken == other.purchaseToken &&
        this.developerChallenge == other.developerChallenge &&
        this.signatureAlgorithm == other.signatureAlgorithm &&
        this.reservedInfor == other.reservedInfor;
  }

  @override
  int get hashCode => Object.hash(
        purchaseToken,
        developerChallenge,
        signatureAlgorithm,
        reservedInfor,
      );
}
