name: huawei_ml_text_example
description: Demonstrates how to use the Huawei ML Text Plugin.

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_ml_text:
    path: ../
  image_picker: 0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bcr.png
    - assets/doc.png
    - assets/gcr.png
    - assets/text.png
    - assets/user.png
    - assets/icr.png
    - assets/textembed.png
    - assets/textlens.png
