name: huawei_ml_language
description: HUAWEI ML Kit Language Plugin for Flutter. Provides capabilities like translation, sound detection & text to speech.
version: 3.2.0+300
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-mllanguage

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.mllanguage
        pluginClass: HuaweiMlLanguagePlugin
