name: huawei_ml_language
description: Huawei ML Kit Language Plugin for Flutter. Provides capabilities like translation, sound detection & text to speech.
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-mllanguage

version: 3.12.0+300

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.mllanguage
        pluginClass: HuaweiMlLanguagePlugin
