name: huawei_nearbyservice_example
description: Demonstrates how to use the Huawei Nearby Service plugin.

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_nearbyservice:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  