name: huawei_adsprime_example
description: Demonstrates how to use the Huawei AdsPrime Kit plugin.

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_adsprime:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
