name: huawei_dtm_example
description: Demonstrates how to use the Huawei DTM plugin.
version: 6.1.0+301

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  huawei_dtm:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/hw_icon.png
