name: huawei_contactshield_example
description: Demonstrates how to use the Huawei Contact Shield plugin.
version: 6.1.0+301
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: 4.1.3

  huawei_contactshield:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
