name: huawei_contactshield_example
description: Demonstrates how to use the Huawei Contact Shield plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_contactshield:
    path: ../
  file_picker: 4.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
