name: huawei_ml_body
description: HUAWEI ML Kit Body Plugin for Flutter. Provides capabilities like face recognition, liveness & skeleton detection.
version: 3.2.0+300
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-mlbody

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.mlbody
        pluginClass: HuaweiMlBodyPlugin
