name: huawei_ml_body
description: Huawei ML Kit Body Plugin for Flutter. Provides capabilities like face recognition, liveness & skeleton detection.
homepage: https://www.huawei.com
repository: https://github.com/HMS-Core/hms-flutter-plugin/tree/master/flutter-hms-mlbody

version: 3.12.0+301

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.mlbody
        pluginClass: HuaweiMlBodyPlugin
